name: Notify Discord Like GitHub App

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit message to Discord (GitHub App style)
        run: |
          COMMIT_URL="${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
          AVATAR_URL="https://avatars.githubusercontent.com/${{ github.actor }}"
          CONTENT=$(jq -n \
            --arg username "${{ github.actor }}" \
            --arg avatar "$AVATAR_URL" \
            --arg commit_msg "${{ github.event.head_commit.message }}" \
            --arg repo "${{ github.repository }}" \
            --arg branch "${{ github.ref_name }}" \
            --arg commit_url "$COMMIT_URL" \
            '{
              username: "GitHub",
              avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              embeds: [
                {
                  title: "\($repo): \($branch)",
                  url: $commit_url,
                  description: $commit_msg,
                  color: 7506394,
                  author: {
                    name: $username,
                    icon_url: $avatar
                  },
                  footer: {
                    text: "Commit by \($username)"
                  }
                }
              ]
            }')
          curl -H "Content-Type: application/json" \
               -d "$CONTENT" \
               ${{ secrets.DISCORD_WEBHOOK }}
